### ISSUE TITLE
Guru Error with akmenu when touch the folders if there is a .nds/.gbc/... file in the next folder

### ISSUE THREAD

**Issue by R-YaTian** [RocketRobz/TWiLightMenu#415]
Read the title.
If you press A fastly when open a folder if there are these files.A Guru Error Also.

**Comment by chyyran** [comment]
This may have been fixed with #423, which properly allocates enough buffer to read filenames in.

**Comment by R-YaTian** [comment]
I checked it and the issue not yet fixed.Then i found that you need touch the folder‘s icon to make it Guru Error.And touch the icon will not only enter the next folder but open the first file or folder in next folder.If there is a .nds file in next folder,the Guru Error will happen.

**Comment by R-YaTian** [comment]
> This may have been fixed with #423, which properly allocates enough buffer to read filenames in.
I checked it and the issue not yet fixed.Then i found that you need touch the folder‘s icon to make it Guru Error.And touch the icon will not only enter the next folder but open the first file or folder in next folder.If there is a .nds file in next folder,the Guru Error will happen.

**Comment by chyyran** [comment]
Managed to reproduce. Will look into this.

**Comment by chyyran** [comment]
Fixed by #428

**Comment by R-YaTian** [comment]
> Fixed by #428

Good job.I tested it and no Error happen up to now.

**Comment by NightYoshi370** [comment]
Alright, well in that case, I'll be closing this
